create extension if not exists pgcrypto;
create type public.app_role as enum ('student','instructor','academic','admin','finance','executive','superadmin');
create type public.application_status as enum ('submitted','contacted','placement_scheduled','placement_complete','offered','accepted','rejected','withdrawn');
create type public.enrollment_status as enum ('pending_payment','active','completed','cancelled');
create type public.invoice_status as enum ('issued','partially_paid','paid','void','refunded');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null,email text,phone text,city text,role app_role not null default 'student',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.applications(id uuid primary key default gen_random_uuid(),application_number text not null unique,full_name text not null,email text not null,phone text not null,city text,language text not null check(language in ('English','Japanese','German')),level text not null,goal text not null,delivery_mode text not null,notes text,status application_status not null default 'submitted',marketing_consent boolean not null default false,assigned_to uuid references profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.programs(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,language text not null,framework text not null,level text not null,description text not null,learning_outcomes jsonb not null default '[]',published boolean not null default true,sort_order int not null default 0);
create table public.cohorts(id uuid primary key default gen_random_uuid(),program_id uuid not null references programs(id),code text not null unique,name text not null,starts_on date not null,ends_on date not null,capacity int not null check(capacity>0),delivery_mode text not null,status text not null default 'draft',instructor_id uuid references profiles(id));
create table public.enrollments(id uuid primary key default gen_random_uuid(),student_id uuid not null references profiles(id),cohort_id uuid not null references cohorts(id),status enrollment_status not null default 'pending_payment',enrolled_at timestamptz,unique(student_id,cohort_id));
create table public.class_sessions(id uuid primary key default gen_random_uuid(),cohort_id uuid not null references cohorts(id) on delete cascade,title text not null,starts_at timestamptz not null,ends_at timestamptz not null,location text,meeting_url text,check(ends_at>starts_at));
create table public.attendance(session_id uuid references class_sessions(id) on delete cascade,student_id uuid references profiles(id),status text not null check(status in ('present','late','excused','absent')),notes text,recorded_by uuid references profiles(id),recorded_at timestamptz not null default now(),primary key(session_id,student_id));
create table public.modules(id uuid primary key default gen_random_uuid(),program_id uuid not null references programs(id) on delete cascade,title text not null,description text,sort_order int not null);
create table public.materials(id uuid primary key default gen_random_uuid(),module_id uuid not null references modules(id) on delete cascade,title text not null,kind text not null,content_url text,body text,sort_order int not null default 0,published boolean not null default false);
create table public.material_progress(material_id uuid references materials(id) on delete cascade,student_id uuid references profiles(id),completed_at timestamptz not null default now(),primary key(material_id,student_id));
create table public.assignments(id uuid primary key default gen_random_uuid(),cohort_id uuid not null references cohorts(id) on delete cascade,title text not null,instructions text not null,due_at timestamptz,max_score numeric not null default 100,weight numeric not null default 0);
create table public.submissions(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references assignments(id) on delete cascade,student_id uuid not null references profiles(id),submission_url text,submission_text text,status text not null default 'submitted',submitted_at timestamptz not null default now(),unique(assignment_id,student_id));
create table public.grades(id uuid primary key default gen_random_uuid(),submission_id uuid not null unique references submissions(id) on delete cascade,score numeric not null,feedback text,graded_by uuid references profiles(id),graded_at timestamptz not null default now());
create table public.invoices(id uuid primary key default gen_random_uuid(),invoice_number text not null unique,student_id uuid not null references profiles(id),enrollment_id uuid references enrollments(id),amount numeric(14,2) not null check(amount>=0),currency char(3) not null default 'IDR',status invoice_status not null default 'issued',due_at timestamptz,created_at timestamptz not null default now());
create table public.payment_confirmations(id uuid primary key default gen_random_uuid(),invoice_id uuid not null references invoices(id),student_id uuid not null references profiles(id),sender_name text not null,bank_name text not null,transfer_date date not null,amount numeric(14,2) not null,proof_url text not null,status text not null default 'submitted',verified_by uuid references profiles(id),verified_at timestamptz,created_at timestamptz not null default now());
create table public.certificates(id uuid primary key default gen_random_uuid(),enrollment_id uuid not null unique references enrollments(id),student_id uuid not null references profiles(id),certificate_number text not null unique,verification_token uuid not null default gen_random_uuid() unique,issued_at timestamptz not null default now(),revoked_at timestamptz);
create table public.announcements(id uuid primary key default gen_random_uuid(),cohort_id uuid references cohorts(id),title text not null,body text not null,published_at timestamptz not null default now(),created_by uuid references profiles(id));
create table public.audit_logs(id bigint generated always as identity primary key,actor_id uuid references profiles(id),action text not null,entity_type text not null,entity_id text,metadata jsonb not null default '{}',created_at timestamptz not null default now());

create or replace function public.current_role() returns app_role language sql stable security definer set search_path=public as $$ select role from profiles where id=auth.uid() $$;
create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select coalesce(current_role() in ('instructor','academic','admin','finance','executive','superadmin'),false) $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into profiles(id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','Pengguna'),new.email); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table profiles enable row level security;alter table applications enable row level security;alter table programs enable row level security;alter table cohorts enable row level security;alter table enrollments enable row level security;alter table class_sessions enable row level security;alter table attendance enable row level security;alter table modules enable row level security;alter table materials enable row level security;alter table material_progress enable row level security;alter table assignments enable row level security;alter table submissions enable row level security;alter table grades enable row level security;alter table invoices enable row level security;alter table payment_confirmations enable row level security;alter table certificates enable row level security;alter table announcements enable row level security;alter table audit_logs enable row level security;

create policy profiles_self_read on profiles for select using(id=auth.uid() or is_staff());
create policy profiles_self_update on profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy staff_profiles_manage on profiles for all using(current_role() in ('admin','superadmin')) with check(current_role() in ('admin','superadmin'));
create policy programs_public_read on programs for select using(published or is_staff());
create policy programs_academic_manage on programs for all using(current_role() in ('academic','admin','superadmin')) with check(current_role() in ('academic','admin','superadmin'));
create policy cohorts_enrolled_read on cohorts for select using(is_staff() or exists(select 1 from enrollments e where e.cohort_id=id and e.student_id=auth.uid()));
create policy cohorts_staff_manage on cohorts for all using(is_staff()) with check(is_staff());
create policy enrollments_read on enrollments for select using(student_id=auth.uid() or is_staff());
create policy enrollments_staff_manage on enrollments for all using(is_staff()) with check(is_staff());
create policy sessions_read on class_sessions for select using(is_staff() or exists(select 1 from enrollments e where e.cohort_id=cohort_id and e.student_id=auth.uid()));
create policy sessions_staff_manage on class_sessions for all using(is_staff()) with check(is_staff());
create policy attendance_read on attendance for select using(student_id=auth.uid() or is_staff());
create policy attendance_staff_manage on attendance for all using(is_staff()) with check(is_staff());
create policy learning_read_modules on modules for select using(is_staff() or exists(select 1 from programs p join cohorts c on c.program_id=p.id join enrollments e on e.cohort_id=c.id where p.id=program_id and e.student_id=auth.uid()));
create policy learning_read_materials on materials for select using(published and exists(select 1 from modules m join cohorts c on c.program_id=m.program_id join enrollments e on e.cohort_id=c.id where m.id=module_id and e.student_id=auth.uid()) or is_staff());
create policy material_progress_self on material_progress for all using(student_id=auth.uid() or is_staff()) with check(student_id=auth.uid() or is_staff());
create policy assignments_read on assignments for select using(is_staff() or exists(select 1 from enrollments e where e.cohort_id=cohort_id and e.student_id=auth.uid()));
create policy submissions_self on submissions for all using(student_id=auth.uid() or is_staff()) with check(student_id=auth.uid() or is_staff());
create policy grades_read on grades for select using(is_staff() or exists(select 1 from submissions s where s.id=submission_id and s.student_id=auth.uid()));
create policy grades_staff_manage on grades for all using(is_staff()) with check(is_staff());
create policy invoices_read on invoices for select using(student_id=auth.uid() or current_role() in ('finance','admin','executive','superadmin'));
create policy payments_read on payment_confirmations for select using(student_id=auth.uid() or current_role() in ('finance','admin','executive','superadmin'));
create policy payments_staff_update on payment_confirmations for update using(current_role() in ('finance','admin','superadmin'));
create policy certificates_read on certificates for select using(student_id=auth.uid() or is_staff());
create policy announcements_read on announcements for select using(is_staff() or cohort_id is null or exists(select 1 from enrollments e where e.cohort_id=cohort_id and e.student_id=auth.uid()));
create policy applications_staff_only on applications for select using(is_staff());
create policy applications_staff_update on applications for update using(is_staff()) with check(is_staff());
create policy audit_staff_read on audit_logs for select using(current_role() in ('admin','executive','superadmin'));

create index enrollments_student_idx on enrollments(student_id,status);create index sessions_cohort_start_idx on class_sessions(cohort_id,starts_at);create index assignments_cohort_due_idx on assignments(cohort_id,due_at);create index invoices_student_status_idx on invoices(student_id,status);create index applications_status_created_idx on applications(status,created_at desc);

insert into programs(code,name,language,framework,level,description,sort_order) values
('EN-A1','English A1','English','CEFR','A1','Komunikasi dasar dan kebutuhan sehari-hari.',1),('EN-A2','English A2','English','CEFR','A2','Komunikasi rutin dan teks pendek.',2),('EN-B1','English B1','English','CEFR','B1','Komunikasi mandiri untuk studi dan perjalanan.',3),('EN-B2','English B2','English','CEFR','B2','Komunikasi kompleks akademik dan profesional.',4),('EN-C1','English C1','English','CEFR','C1','Penggunaan fleksibel tingkat lanjut.',5),('EN-C2','English C2','English','CEFR','C2','Kemahiran sangat tinggi dan presisi.',6),
('JP-N5','Japanese N5','Japanese','JLPT','N5','Fondasi hiragana, katakana, kanji, dan percakapan.',11),('JP-N4','Japanese N4','Japanese','JLPT','N4','Komunikasi dasar dan teks sederhana.',12),('JP-N3','Japanese N3','Japanese','JLPT','N3','Komunikasi menengah dalam situasi sehari-hari.',13),('JP-N2','Japanese N2','Japanese','JLPT','N2','Komunikasi studi dan kerja tingkat lanjut.',14),('JP-N1','Japanese N1','Japanese','JLPT','N1','Kemahiran akademik dan profesional.',15),
('DE-A1','German A1','German','CEFR/Goethe','A1','Komunikasi dasar dan perkenalan.',21),('DE-A2','German A2','German','CEFR/Goethe','A2','Rutinitas dan komunikasi sehari-hari.',22),('DE-B1','German B1','German','CEFR/Goethe','B1','Komunikasi mandiri dan persiapan Ausbildung.',23),('DE-B2','German B2','German','CEFR/Goethe','B2','Komunikasi studi dan profesional.',24),('DE-C1','German C1','German','CEFR/Goethe','C1','Bahasa akademik dan profesional tingkat lanjut.',25),('DE-C2','German C2','German','CEFR/Goethe','C2','Kemahiran sangat tinggi dan presisi.',26);
