-- KLI multi-skill academic assessment layer
create table public.assessment_rubrics(id uuid primary key default gen_random_uuid(),code text unique not null,title text not null,skill text not null,scale_max numeric not null default 20,version text not null default '1.0',criteria jsonb not null,created_at timestamptz not null default now());
create table public.assessment_blueprints(id uuid primary key default gen_random_uuid(),test_id uuid unique not null references public.assessment_tests(id) on delete cascade,standard_reference text not null,intended_use text not null,target_population text not null,skills jsonb not null,min_objective_items int not null default 20,requires_human_rating boolean not null default true,cut_score_method text not null default 'Modified Angoff after pilot',created_at timestamptz not null default now());
create table public.assessment_tasks(id uuid primary key default gen_random_uuid(),test_id uuid not null references public.assessment_tests(id) on delete cascade,skill text not null check(skill in ('reading','listening','writing','speaking')),stimulus text,prompt text not null,min_words int,max_words int,duration_seconds int,rubric_id uuid references public.assessment_rubrics(id),sort_order int not null,published boolean not null default true);
create table public.assessment_task_responses(id uuid primary key default gen_random_uuid(),attempt_id uuid not null references public.assessment_attempts(id) on delete cascade,task_id uuid not null references public.assessment_tasks(id),response_text text,file_path text,status text not null default 'pending_review' check(status in ('pending_review','rated','returned')),score numeric check(score is null or score between 0 and 100),rated_by uuid references public.profiles(id),rated_at timestamptz,feedback text,unique(attempt_id,task_id));
create table public.assessment_reviews(id uuid primary key default gen_random_uuid(),test_id uuid not null references public.assessment_tests(id) on delete cascade,reviewer_id uuid not null references public.profiles(id),review_type text not null check(review_type in ('content','language','level','bias','technical','psychometric')),decision text not null check(decision in ('approved','revision_required')),notes text not null,created_at timestamptz not null default now());
create table public.assessment_item_statistics(question_id uuid primary key references public.assessment_questions(id) on delete cascade,sample_size int not null default 0,difficulty numeric,discrimination numeric,distractor_analysis jsonb,reliability_contribution numeric,last_calculated_at timestamptz);
alter table public.assessment_blueprints enable row level security;alter table public.assessment_tasks enable row level security;alter table public.assessment_task_responses enable row level security;alter table public.assessment_reviews enable row level security;alter table public.assessment_item_statistics enable row level security;
create policy blueprint_staff_read on public.assessment_blueprints for select using(public.is_staff());
create policy tasks_staff_read on public.assessment_tasks for select using(public.is_staff());
create policy responses_owner_read on public.assessment_task_responses for select using(public.is_staff() or exists(select 1 from public.assessment_attempts a where a.id=attempt_id and a.student_id=auth.uid()));
create policy reviews_staff on public.assessment_reviews for all using(public.current_role() in ('academic','admin','superadmin')) with check(public.current_role() in ('academic','admin','superadmin'));
create policy stats_staff on public.assessment_item_statistics for select using(public.is_staff());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('assessment-responses','assessment-responses',false,15728640,array['audio/webm','audio/mpeg','audio/mp4','audio/wav']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy assessment_audio_owner_insert on storage.objects for insert to authenticated with check(bucket_id='assessment-responses' and (storage.foldername(name))[1]=auth.uid()::text);
create policy assessment_audio_staff_read on storage.objects for select to authenticated using(bucket_id='assessment-responses' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_staff()));
insert into public.assessment_rubrics(code,title,skill,criteria) values
('WRITING','Analytic Writing Rubric','writing','[{"name":"Task achievement","max":5},{"name":"Organization and cohesion","max":5},{"name":"Range","max":5},{"name":"Accuracy","max":5}]'),
('SPEAKING','Analytic Speaking Rubric','speaking','[{"name":"Task fulfilment","max":5},{"name":"Fluency and coherence","max":5},{"name":"Range","max":5},{"name":"Accuracy and pronunciation","max":5}]'),
('COMPREHENSION','Constructed Response Comprehension','reading/listening','[{"name":"Main idea","max":5},{"name":"Relevant detail","max":5},{"name":"Inference","max":5},{"name":"Language clarity","max":5}]');
insert into public.assessment_blueprints(test_id,standard_reference,intended_use,target_population,skills,min_objective_items)
select id,case when language='Japanese' then 'JLPT official level summary plus KLI productive-skills extension' else 'CEFR Companion Volume 2020' end,'KLI holistic placement; not an official external-exam score',language||' learners targeting '||level,'{"objective":20,"reading":20,"listening":20,"writing":20,"speaking":20}',20 from public.assessment_tests where test_type='placement';
with skill_rows(skill,sort_order,rubric_code) as (values ('reading',1,'COMPREHENSION'),('listening',2,'COMPREHENSION'),('writing',3,'WRITING'),('speaking',4,'SPEAKING'))
insert into public.assessment_tasks(test_id,skill,stimulus,prompt,min_words,max_words,duration_seconds,rubric_id,sort_order)
select t.id,s.skill,
case s.skill when 'reading' then 'Original KLI level-aligned text about identity, daily life, study, work, society, or an abstract issue appropriate to '||t.language||' '||t.level||'.' when 'listening' then 'Original KLI level-aligned script containing a purpose, supporting details, and a next step for '||t.language||' '||t.level||'.' else null end,
case s.skill when 'reading' then 'Summarize the main idea and identify two supporting details.' when 'listening' then 'Listen twice, state the purpose, and report two important details.' when 'writing' then 'Write a coherent level-appropriate response to the stated topic, with relevant detail and clear organization.' when 'speaking' then 'Record a 1–3 minute level-appropriate response, explain your ideas, and include an example.' end,
case when s.skill in ('reading','listening') then 30 when s.skill='writing' then case when t.level in ('A1','N5') then 40 when t.level in ('A2','N4') then 60 when t.level in ('B1','N3') then 100 when t.level in ('B2','N2') then 150 when t.level in ('C1','N1') then 220 else 280 end end,
case when s.skill in ('reading','listening') then 180 when s.skill='writing' then case when t.level in ('A1','N5') then 80 when t.level in ('A2','N4') then 120 when t.level in ('B1','N3') then 200 when t.level in ('B2','N2') then 300 when t.level in ('C1','N1') then 440 else 560 end end,
case when s.skill='speaking' then 180 else 600 end,r.id,s.sort_order
from public.assessment_tests t cross join skill_rows s join public.assessment_rubrics r on r.code=s.rubric_code where t.test_type='placement';
create or replace view public.assessment_quality_summary with (security_invoker=true) as select t.id,t.code,t.language,t.level,t.test_type,t.version,t.review_status,count(distinct q.id)::int question_count,count(distinct k.id)::int task_count,coalesce(b.min_objective_items,20) min_objective_items,(count(distinct q.id)>=coalesce(b.min_objective_items,20) and count(distinct k.id)>=4) content_complete from public.assessment_tests t left join public.assessment_questions q on q.test_id=t.id left join public.assessment_tasks k on k.test_id=t.id left join public.assessment_blueprints b on b.test_id=t.id group by t.id,b.min_objective_items;
