-- Complete specialist diagnostic forms without claiming equivalence to official examinations.
alter table public.assessment_blueprints add column if not exists min_tasks int not null default 4;
with mappings(target_code,source_code,reference_name,skills,min_tasks) as (values
('EN-IELTS-READINESS','EN-B2-PLACEMENT','IELTS official four-section format; KLI diagnostic only','{"objective":20,"reading":20,"listening":20,"writing":20,"speaking":20}'::jsonb,4),
('EN-TOEFL-READINESS','EN-B2-PLACEMENT','ETS TOEFL iBT four-skill content; KLI diagnostic only','{"objective":20,"reading":20,"listening":20,"writing":20,"speaking":20}'::jsonb,4),
('JP-JLPT-READINESS','JP-N3-PLACEMENT','JLPT official language knowledge, reading, and listening sections; KLI diagnostic only','{"objective":40,"reading":30,"listening":30}'::jsonb,2),
('JP-KANA-KANJI','JP-N5-PLACEMENT','KLI foundational kana and kanji diagnostic','{"objective":100}'::jsonb,0),
('DE-GOETHE-READINESS','DE-B2-PLACEMENT','Goethe Lesen, Hören, Schreiben, Sprechen modules; KLI diagnostic only','{"objective":20,"reading":20,"listening":20,"writing":20,"speaking":20}'::jsonb,4),
('DE-AUSBILDUNG-COMM','DE-B1-PLACEMENT','CEFR workplace communication; KLI vocational diagnostic','{"objective":20,"reading":15,"listening":15,"writing":25,"speaking":25}'::jsonb,4))
insert into public.assessment_blueprints(test_id,standard_reference,intended_use,target_population,skills,min_objective_items,min_tasks)
select target.id,m.reference_name,'Readiness/support-needs screening only; not an official score or admission guarantee',target.language||' learners preparing for '||target.framework,m.skills,20,m.min_tasks from mappings m join public.assessment_tests target on target.code=m.target_code;
with mappings(target_code,source_code) as (values ('EN-IELTS-READINESS','EN-B2-PLACEMENT'),('EN-TOEFL-READINESS','EN-B2-PLACEMENT'),('JP-JLPT-READINESS','JP-N3-PLACEMENT'),('JP-KANA-KANJI','JP-N5-PLACEMENT'),('DE-GOETHE-READINESS','DE-B2-PLACEMENT'),('DE-AUSBILDUNG-COMM','DE-B1-PLACEMENT'))
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency)
select target.id,q.prompt,q.options,q.correct_option,q.points,q.sort_order,q.competency from mappings m join public.assessment_tests source on source.code=m.source_code join public.assessment_tests target on target.code=m.target_code join public.assessment_questions q on q.test_id=source.id and q.sort_order>=4;
with mappings(target_code,source_code,allowed_skills) as (values
('EN-IELTS-READINESS','EN-B2-PLACEMENT',array['reading','listening','writing','speaking']),('EN-TOEFL-READINESS','EN-B2-PLACEMENT',array['reading','listening','writing','speaking']),('JP-JLPT-READINESS','JP-N3-PLACEMENT',array['reading','listening']),('DE-GOETHE-READINESS','DE-B2-PLACEMENT',array['reading','listening','writing','speaking']),('DE-AUSBILDUNG-COMM','DE-B1-PLACEMENT',array['reading','listening','writing','speaking']))
insert into public.assessment_tasks(test_id,skill,stimulus,prompt,min_words,max_words,duration_seconds,rubric_id,sort_order,published)
select target.id,k.skill,k.stimulus,k.prompt,k.min_words,k.max_words,k.duration_seconds,k.rubric_id,k.sort_order,k.published from mappings m join public.assessment_tests source on source.code=m.source_code join public.assessment_tests target on target.code=m.target_code join public.assessment_tasks k on k.test_id=source.id and k.skill=any(m.allowed_skills);
drop view if exists public.assessment_quality_summary;
create or replace view public.assessment_quality_summary with (security_invoker=true) as select t.id,t.code,t.language,t.level,t.test_type,t.version,t.review_status,count(distinct q.id)::int question_count,count(distinct k.id)::int task_count,coalesce(b.min_objective_items,20) min_objective_items,coalesce(b.min_tasks,4) min_tasks,(count(distinct q.id)>=coalesce(b.min_objective_items,20) and count(distinct k.id)>=coalesce(b.min_tasks,4)) content_complete from public.assessment_tests t left join public.assessment_questions q on q.test_id=t.id left join public.assessment_tasks k on k.test_id=t.id left join public.assessment_blueprints b on b.test_id=t.id group by t.id,b.min_objective_items,b.min_tasks;
