-- High-stakes controls: level descriptors, stable audio, competency coverage, and dual rating.
create table public.assessment_level_descriptors(language text not null,level text not null,framework text not null,descriptors jsonb not null,limitations text not null,primary key(language,level));
alter table public.assessment_level_descriptors enable row level security;
create policy level_descriptors_public_read on public.assessment_level_descriptors for select using(true);
alter table public.assessment_tasks add column if not exists audio_file_path text;
alter table public.assessment_tasks add column if not exists transcript_release text not null default 'after_submit' check(transcript_release in ('never','after_submit','immediate'));
create table public.assessment_ratings(id uuid primary key default gen_random_uuid(),response_id uuid not null references public.assessment_task_responses(id) on delete cascade,rater_id uuid not null references public.profiles(id),criteria_scores jsonb not null default '{}',total_score numeric not null check(total_score between 0 and 100),feedback text not null,created_at timestamptz not null default now(),unique(response_id,rater_id));
alter table public.assessment_ratings enable row level security;
create policy ratings_staff_read on public.assessment_ratings for select using(public.is_staff());
create policy ratings_rater_insert on public.assessment_ratings for insert with check(rater_id=auth.uid() and public.current_role() in ('instructor','academic','admin','superadmin'));
alter table public.assessment_task_responses drop constraint if exists assessment_task_responses_status_check;
alter table public.assessment_task_responses add constraint assessment_task_responses_status_check check(status in ('pending_review','rated','needs_adjudication','returned'));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('assessment-assets','assessment-assets',false,20971520,array['audio/mpeg','audio/mp4','audio/wav','audio/ogg']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy assessment_assets_staff_insert on storage.objects for insert to authenticated with check(bucket_id='assessment-assets' and public.current_role() in ('academic','admin','superadmin'));
create policy assessment_assets_staff_read on storage.objects for select to authenticated using(bucket_id='assessment-assets' and public.is_staff());
insert into public.assessment_level_descriptors(language,level,framework,descriptors,limitations) values
('English','A1','CEFR','{"reading":"understands names, familiar words, and very short simple texts","listening":"recognizes familiar words and basic phrases delivered slowly","writing":"produces short basic personal information","speaking":"uses simple memorized expressions with support"}','Not evidence of independent communication in unfamiliar situations.'),
('English','A2','CEFR','{"reading":"understands short predictable everyday texts","listening":"understands high-frequency information on immediate needs","writing":"writes short connected messages on familiar matters","speaking":"handles simple routine exchanges"}','Complex explanations and sustained interaction are outside scope.'),
('English','B1','CEFR','{"reading":"understands straightforward factual texts on familiar interests","listening":"follows clear standard speech on familiar matters","writing":"produces connected text and reasons for opinions","speaking":"manages familiar travel, study, and work situations"}','Nuanced academic or professional performance requires higher evidence.'),
('English','B2','CEFR','{"reading":"understands complex factual and argumentative texts","listening":"follows extended speech with clear organization","writing":"develops a structured argument with relevant detail","speaking":"interacts with fluency and supports viewpoints"}','Specialized high-stakes domains require domain-specific assessment.'),
('English','C1','CEFR','{"reading":"understands demanding texts and implicit meaning","listening":"follows extended discourse even when structure is not explicit","writing":"produces well-structured detailed text with controlled style","speaking":"uses language flexibly for academic and professional purposes"}','C1 does not imply native-like mastery in every domain.'),
('English','C2','CEFR','{"reading":"interprets virtually all complex written forms critically","listening":"understands rapid natural speech across varieties with adjustment","writing":"creates precise nuanced text for sophisticated purposes","speaking":"expresses subtle distinctions spontaneously and coherently"}','Performance may still vary by specialist knowledge and context.'),
('German','A1','CEFR','{"reading":"versteht vertraute Wörter und sehr kurze Texte","listening":"erkennt langsam gesprochene elementare Wendungen","writing":"schreibt kurze persönliche Angaben","speaking":"verwendet einfache gelernte Ausdrücke mit Hilfe"}','Keine Aussage über selbstständige Kommunikation in unbekannten Situationen.'),
('German','A2','CEFR','{"reading":"versteht kurze vorhersehbare Alltagstexte","listening":"versteht häufige Informationen zu unmittelbaren Bedürfnissen","writing":"schreibt kurze verbundene Mitteilungen","speaking":"bewältigt einfache routinemäßige Gespräche"}','Komplexe Erklärungen liegen außerhalb dieses Niveaus.'),
('German','B1','CEFR','{"reading":"versteht klare Sachtexte zu vertrauten Themen","listening":"folgt klarer Standardsprache in vertrauten Bereichen","writing":"verfasst zusammenhängende Texte und begründet Meinungen","speaking":"bewältigt typische Reise-, Lern- und Arbeitssituationen"}','Fachsprache und nuancierte Argumentation benötigen weitere Evidenz.'),
('German','B2','CEFR','{"reading":"versteht komplexe Sach- und Argumentationstexte","listening":"folgt längerem klar gegliedertem Diskurs","writing":"entwickelt strukturierte Argumente mit Details","speaking":"interagiert flüssig und begründet Standpunkte"}','Spezialisierte Kontexte benötigen zusätzliche Aufgaben.'),
('German','C1','CEFR','{"reading":"versteht anspruchsvolle Texte und implizite Bedeutung","listening":"folgt komplexem Diskurs auch ohne deutliche Gliederung","writing":"verfasst detaillierte, stilistisch kontrollierte Texte","speaking":"verwendet Sprache flexibel in Studium und Beruf"}','Keine automatische Gleichsetzung mit muttersprachlicher Kompetenz.'),
('German','C2','CEFR','{"reading":"interpretiert nahezu alle komplexen Textsorten kritisch","listening":"versteht schnelles natürliches Sprechen in vielen Varietäten","writing":"formuliert präzise und nuanciert für anspruchsvolle Zwecke","speaking":"drückt feine Bedeutungsunterschiede spontan aus"}','Leistung bleibt vom Fachwissen und Kontext abhängig.'),
('Japanese','N5','JLPT + KLI extension','{"language_knowledge":"recognizes basic kana, kanji, vocabulary, and sentence patterns","reading":"understands typical short basic sentences","listening":"understands short slow conversations about daily life","productive_extension":"provides very short supported personal responses"}','JLPT itself does not assess speaking or writing; KLI productive evidence is separate.'),
('Japanese','N4','JLPT + KLI extension','{"language_knowledge":"uses basic vocabulary, kanji, and common grammar","reading":"understands passages on familiar daily topics","listening":"follows slow everyday conversations","productive_extension":"produces short connected responses on familiar matters"}','KLI productive evidence must not be reported as an official JLPT component.'),
('Japanese','N3','JLPT + KLI extension','{"language_knowledge":"handles intermediate vocabulary, kanji, and grammar","reading":"understands everyday materials and summaries of more difficult texts","listening":"follows coherent everyday speech near natural speed","productive_extension":"explains familiar experiences and opinions"}','N3 is a bridge level; domain and interaction demands may vary.'),
('Japanese','N2','JLPT + KLI extension','{"language_knowledge":"handles broad vocabulary, kanji, and complex grammar","reading":"understands articles and commentaries on general topics","listening":"follows coherent speech at near-natural speed across settings","productive_extension":"communicates structured views in study and work contexts"}','Productive KLI ratings are not official JLPT scores.'),
('Japanese','N1','JLPT + KLI extension','{"language_knowledge":"interprets advanced vocabulary, kanji, grammar, and nuance","reading":"understands logically complex and abstract writing","listening":"follows natural-speed coherent discourse across contexts","productive_extension":"discusses abstract issues with precision and appropriate register"}','N1 receptive performance does not by itself establish professional productive mastery.');
create or replace view public.assessment_competency_coverage with (security_invoker=true) as select t.id test_id,count(distinct q.competency)::int competency_count,array_agg(distinct q.competency) competencies from public.assessment_tests t left join public.assessment_questions q on q.test_id=t.id group by t.id;
create or replace view public.assessment_quality_summary with (security_invoker=true) as select t.id,t.code,t.language,t.level,t.test_type,t.version,t.review_status,t.validation_status,t.pilot_sample_size,t.reliability,count(distinct q.id)::int question_count,count(distinct k.id)::int task_count,coalesce(b.min_objective_items,20) min_objective_items,coalesce(b.min_tasks,4) min_tasks,count(distinct q.competency)::int competency_count,(count(distinct case when k.skill='listening' then k.id end)=0 or count(distinct case when k.skill='listening' and k.audio_file_path is not null then k.id end)=count(distinct case when k.skill='listening' then k.id end)) audio_ready,(count(distinct q.id)>=coalesce(b.min_objective_items,20) and count(distinct k.id)>=coalesce(b.min_tasks,4) and count(distinct q.competency)>=case when b.min_tasks=0 then 2 else 5 end and (count(distinct case when k.skill='listening' then k.id end)=0 or count(distinct case when k.skill='listening' and k.audio_file_path is not null then k.id end)=count(distinct case when k.skill='listening' then k.id end))) content_complete from public.assessment_tests t left join public.assessment_questions q on q.test_id=t.id left join public.assessment_tasks k on k.test_id=t.id left join public.assessment_blueprints b on b.test_id=t.id group by t.id,b.min_objective_items,b.min_tasks;
