-- KLI-original Academic IELTS preparation form aligned to the licensed Cambridge reference structure.
insert into public.assessment_source_register(file_name,sha256,level,material_role,file_type,rights_status,commercial_use_allowed,license_reference,source_owner)
values('Cambridge IELTS 5.pdf','149de185812b54ebc004878f87eddd66d70903d96000dd1dcc4a71eef48d79bd','Academic','reference_book','pdf','licensed_user_attested',true,'User confirmed written commercial permission on 2026-09-17; archive the license document before validated publication.','Cambridge University Press')
on conflict(file_name) do update set rights_status=excluded.rights_status,commercial_use_allowed=true,license_reference=excluded.license_reference;
insert into public.assessment_tests(code,language,framework,level,test_type,title,description,duration_minutes,pass_score,published,version,review_status,usage_scope,validation_status,max_attempts,cooldown_hours)
values('EN-IELTS-ACADEMIC-PRACTICE','English','IELTS Academic preparation','B2–C1','certification_readiness','KLI Academic English Four-Skills Practice','A complete KLI-original IELTS Academic preparation form: Listening 40, Reading 40, Writing 2 tasks, and Speaking 3 parts. Not an official IELTS test or band score.',164,70,true,'1.0','academic_review','practice','content_ready',3,72)
on conflict(code) do update set title=excluded.title,description=excluded.description,duration_minutes=164,published=true,usage_scope='practice';
insert into public.assessment_blueprints(test_id,standard_reference,intended_use,target_population,skills,min_objective_items,requires_human_rating,cut_score_method)
select id,'Current IELTS Academic four-section format; Cambridge IELTS 5 licensed structural benchmark; KLI-original content','Commercial IELTS Academic preparation practice only','B2-C1 learners preparing for academic study','{"listening":40,"reading":40,"writing_tasks":2,"speaking_parts":3}'::jsonb,80,true,'KLI readiness profile; no official IELTS band conversion' from public.assessment_tests where code='EN-IELTS-ACADEMIC-PRACTICE'
on conflict(test_id) do update set standard_reference=excluded.standard_reference,intended_use=excluded.intended_use,skills=excluded.skills,min_objective_items=80,requires_human_rating=true;
delete from public.assessment_questions where test_id=(select id from public.assessment_tests where code='EN-IELTS-ACADEMIC-PRACTICE');
delete from public.assessment_tasks where test_id=(select id from public.assessment_tests where code='EN-IELTS-ACADEMIC-PRACTICE');

insert into public.assessment_sections(test_id,code,title,score_group,duration_minutes,target_item_count,task_taxonomy,sort_order,source_alignment) select id,'listening','Listening','listening',30,40,'[]'::jsonb,1,'Current IELTS Academic structure; KLI-original content' from public.assessment_tests where code='EN-IELTS-ACADEMIC-PRACTICE' on conflict(test_id,code) do update set duration_minutes=excluded.duration_minutes,target_item_count=excluded.target_item_count,sort_order=excluded.sort_order;
insert into public.assessment_sections(test_id,code,title,score_group,duration_minutes,target_item_count,task_taxonomy,sort_order,source_alignment) select id,'reading','Academic Reading','reading',60,40,'[]'::jsonb,2,'Current IELTS Academic structure; KLI-original content' from public.assessment_tests where code='EN-IELTS-ACADEMIC-PRACTICE' on conflict(test_id,code) do update set duration_minutes=excluded.duration_minutes,target_item_count=excluded.target_item_count,sort_order=excluded.sort_order;
insert into public.assessment_sections(test_id,code,title,score_group,duration_minutes,target_item_count,task_taxonomy,sort_order,source_alignment) select id,'writing','Academic Writing','writing',60,2,'[]'::jsonb,3,'Current IELTS Academic structure; KLI-original content' from public.assessment_tests where code='EN-IELTS-ACADEMIC-PRACTICE' on conflict(test_id,code) do update set duration_minutes=excluded.duration_minutes,target_item_count=excluded.target_item_count,sort_order=excluded.sort_order;
insert into public.assessment_sections(test_id,code,title,score_group,duration_minutes,target_item_count,task_taxonomy,sort_order,source_alignment) select id,'speaking','Speaking','speaking',14,3,'[]'::jsonb,4,'Current IELTS Academic structure; KLI-original content' from public.assessment_tests where code='EN-IELTS-ACADEMIC-PRACTICE' on conflict(test_id,code) do update set duration_minutes=excluded.duration_minutes,target_item_count=excluded.target_item_count,sort_order=excluded.sort_order;
insert into public.assessment_stimuli(code,title,content,stimulus_type,audio_script,content_hidden,max_plays,voice_profile) values('KLI-IELTS-L1','Listening Part 1 — Accommodation Enquiry','Transcript withheld during delivery','listening_script','Agent: Good morning, Riverside Student Housing. Student: I am starting a nine-month engineering course in September and need a room from the second of that month. Agent: We have a standard room at 145 pounds per week and a larger en-suite room at 185. Both include internet, but electricity is charged separately. Student: I will take the standard room. I do not have a car, so bicycle storage matters more than parking. Agent: The residence has a locked bicycle room beside Block C. A refundable deposit of 290 pounds is due within five days. Please email a passport copy and your student offer letter. Student: Can I arrive on a Sunday? Agent: Yes, but after six p.m. you must collect the key from security at the east gate. The nearest supermarket is on King Street, about an eight-minute walk away.',true,1,'{"language":"en-GB","rate":0.92,"pitch":1.0}'::jsonb) on conflict(code) do update set audio_script=excluded.audio_script,content_hidden=true,max_plays=1,voice_profile=excluded.voice_profile;
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'When will the student begin renting?','["2 September", "5 September", "9 September", "29 September"]'::jsonb,'2 September',1,1,'listening',0.55,s.id,'form_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'How long is the course?','["Five months", "Nine months", "One year", "Two years"]'::jsonb,'Nine months',1,2,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which room does the student choose?','["Shared studio", "En-suite room", "Standard room", "Family room"]'::jsonb,'Standard room',1,3,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What is included in the weekly rent?','["Electricity", "Parking", "Internet", "Meals"]'::jsonb,'Internet',1,4,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which facility is especially important to the student?','["Car parking", "Bicycle storage", "A gym", "A laundry"]'::jsonb,'Bicycle storage',1,5,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Where is the bicycle room?','["Beside Block C", "At the west gate", "Under the library", "On King Street"]'::jsonb,'Beside Block C',1,6,'listening',0.55,s.id,'map_detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'How much is the deposit?','["145 pounds", "185 pounds", "290 pounds", "435 pounds"]'::jsonb,'290 pounds',1,7,'listening',0.55,s.id,'form_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which two documents must be emailed?','["A passport copy and offer letter", "A bank statement and photograph", "A visa and rental receipt", "A timetable and reference"]'::jsonb,'A passport copy and offer letter',1,8,'listening',0.55,s.id,'matching',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Where are late Sunday keys collected?','["Reception", "The supermarket", "Security at the east gate", "Block C"]'::jsonb,'Security at the east gate',1,9,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'How long is the walk to the supermarket?','["Five minutes", "Eight minutes", "Twelve minutes", "Fifteen minutes"]'::jsonb,'Eight minutes',1,10,'listening',0.55,s.id,'form_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_stimuli(code,title,content,stimulus_type,audio_script,content_hidden,max_plays,voice_profile) values('KLI-IELTS-L2','Listening Part 2 — Museum Volunteer Induction','Transcript withheld during delivery','listening_script','Coordinator: Welcome to the City Museum volunteer programme. The building opens to visitors at ten, but volunteers should arrive by nine thirty and sign in at the staff entrance. Your first two shifts will be in the discovery gallery, where families handle replica objects. Please demonstrate the objects, but do not answer questions about value; direct those to a curator. Blue lockers are available downstairs, and personal bags must not remain behind the desk. At eleven fifteen, one volunteer checks the interactive screens and records faults in the green folder. Lunch is from one until one forty-five in the staff kitchen. In an emergency, guide visitors to the north courtyard, not the main entrance. Next Saturday the museum will host a textile workshop, so the discovery gallery will close at three. Please complete the online safeguarding module before Friday evening.',true,1,'{"language":"en-GB","rate":0.92,"pitch":1.0}'::jsonb) on conflict(code) do update set audio_script=excluded.audio_script,content_hidden=true,max_plays=1,voice_profile=excluded.voice_profile;
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What time should volunteers arrive?','["9:00", "9:30", "10:00", "10:30"]'::jsonb,'9:30',1,11,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Where do volunteers sign in?','["Main entrance", "Discovery gallery", "Staff entrance", "North courtyard"]'::jsonb,'Staff entrance',1,12,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Where will new volunteers work first?','["Textile room", "Discovery gallery", "Ticket office", "Archives"]'::jsonb,'Discovery gallery',1,13,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Who should answer questions about value?','["A curator", "A volunteer", "A security guard", "A visitor"]'::jsonb,'A curator',1,14,'listening',0.55,s.id,'matching',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What colour are the lockers?','["Green", "Blue", "Red", "White"]'::jsonb,'Blue',1,15,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Where are faults recorded?','["Online", "In the green folder", "At reception", "On the screen"]'::jsonb,'In the green folder',1,16,'listening',0.55,s.id,'form_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'When does lunch end?','["1:00", "1:15", "1:40", "1:45"]'::jsonb,'1:45',1,17,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Where should visitors go in an emergency?','["Main entrance", "North courtyard", "Staff kitchen", "South car park"]'::jsonb,'North courtyard',1,18,'listening',0.55,s.id,'map_detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why will the gallery close early next Saturday?','["A private tour", "A textile workshop", "Screen repairs", "Staff training"]'::jsonb,'A textile workshop',1,19,'listening',0.55,s.id,'purpose',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What must be completed before Friday evening?','["A curator interview", "The safeguarding module", "A locker inspection", "The green folder"]'::jsonb,'The safeguarding module',1,20,'listening',0.55,s.id,'form_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_stimuli(code,title,content,stimulus_type,audio_script,content_hidden,max_plays,voice_profile) values('KLI-IELTS-L3','Listening Part 3 — Research Project Meeting','Transcript withheld during delivery','listening_script','Supervisor: Let us refine your study of commuter cycling. Student: I planned to survey everyone entering the central station. Supervisor: That would overrepresent train users. Include the university gate and the hospital entrance as well. Student: I can collect data on Monday and Thursday mornings. Supervisor: Add one evening period because travel patterns change after work. Use the same six questions at every site, and pilot them with ten people before the main survey. Student: Should I ask for names? Supervisor: No. Record age range, journey purpose, distance, and reasons for choosing or avoiding a bicycle. Student: I also wanted to measure air quality. Supervisor: That would make the project too broad. Use the council''s published pollution data instead. Student: I will send the revised questionnaire on the twelfth. Supervisor: Good. Submit the ethics form two days earlier, and book a statistical consultation for the week after data collection.',true,1,'{"language":"en-GB","rate":0.92,"pitch":1.0}'::jsonb) on conflict(code) do update set audio_script=excluded.audio_script,content_hidden=true,max_plays=1,voice_profile=excluded.voice_profile;
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What is the project about?','["Train reliability", "Commuter cycling", "Hospital staffing", "Air pollution equipment"]'::jsonb,'Commuter cycling',1,21,'listening',0.55,s.id,'main_idea',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why is the station sample insufficient?','["It is too small", "It favours train users", "It excludes mornings", "It requires names"]'::jsonb,'It favours train users',1,22,'listening',0.55,s.id,'inference',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which additional sites will be used?','["A school and airport", "University gate and hospital entrance", "Two railway platforms", "Council offices"]'::jsonb,'University gate and hospital entrance',1,23,'listening',0.55,s.id,'matching',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which extra collection period is recommended?','["A weekend afternoon", "One evening", "Friday night", "Sunday morning"]'::jsonb,'One evening',1,24,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'How many survey questions will be used?','["Six", "Eight", "Ten", "Twelve"]'::jsonb,'Six',1,25,'listening',0.55,s.id,'form_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'How many people should join the pilot?','["Five", "Six", "Ten", "Twenty"]'::jsonb,'Ten',1,26,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which information should NOT be collected?','["Age range", "Journey purpose", "Names", "Travel distance"]'::jsonb,'Names',1,27,'listening',0.55,s.id,'negative_detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What should replace direct air-quality measurement?','["A second survey", "Council pollution data", "Hospital records", "A bicycle counter"]'::jsonb,'Council pollution data',1,28,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'When is the revised questionnaire due?','["The tenth", "The twelfth", "Two days after collection", "The following week"]'::jsonb,'The twelfth',1,29,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What should be booked after data collection?','["An ethics interview", "A statistical consultation", "A station visit", "A bicycle repair"]'::jsonb,'A statistical consultation',1,30,'listening',0.55,s.id,'sequence',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_stimuli(code,title,content,stimulus_type,audio_script,content_hidden,max_plays,voice_profile) values('KLI-IELTS-L4','Listening Part 4 — Lecture on Urban Soil','Transcript withheld during delivery','listening_script','Lecturer: Urban soil is often treated as inert material, yet it supports vegetation, stores water, and contains complex communities of organisms. Its properties vary over very short distances because construction, demolition, gardening, and traffic move or compress the soil. Compaction reduces spaces that normally hold air and water, so roots may remain shallow even when nutrients are available. Researchers first map land-use history, then sample at several depths rather than collecting only surface soil. They measure texture, organic matter, acidity, and contaminants such as lead. High contaminant levels do not always require removing all soil. A clean layer can sometimes be added, or food crops can be moved into raised beds with imported soil. Trees present another challenge: species selected for rapid growth may fail during drought if their roots cannot penetrate compacted ground. Current projects therefore combine soil restoration with species selection and long-term monitoring. Community gardens can help researchers observe change, but volunteers need consistent sampling instructions if their data are to be compared across sites.',true,1,'{"language":"en-GB","rate":0.92,"pitch":1.0}'::jsonb) on conflict(code) do update set audio_script=excluded.audio_script,content_hidden=true,max_plays=1,voice_profile=excluded.voice_profile;
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What is the lecture mainly about?','["Urban soil functions and management", "The history of rural farming", "Traffic engineering", "Commercial tree sales"]'::jsonb,'Urban soil functions and management',1,31,'listening',0.55,s.id,'main_idea',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why does urban soil vary over short distances?','["Rainfall is identical", "Human activities move and compress it", "All soil has the same origin", "Roots remove every contaminant"]'::jsonb,'Human activities move and compress it',1,32,'listening',0.55,s.id,'cause_effect',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What does compaction reduce?','["Nutrient prices", "Spaces for air and water", "Land-use records", "Sampling depth"]'::jsonb,'Spaces for air and water',1,33,'listening',0.55,s.id,'sentence_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What should researchers examine first?','["Tree height", "Land-use history", "Volunteer numbers", "Crop prices"]'::jsonb,'Land-use history',1,34,'listening',0.55,s.id,'sequence',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why are samples taken at several depths?','["Surface soil alone may be unrepresentative", "Deep soil has no minerals", "It avoids measuring acidity", "It eliminates mapping"]'::jsonb,'Surface soil alone may be unrepresentative',1,35,'listening',0.55,s.id,'inference',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which contaminant is mentioned?','["Mercury", "Lead", "Salt only", "Plastic fibres"]'::jsonb,'Lead',1,36,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What may be done instead of removing all soil?','["Add a clean layer", "Stop monitoring", "Increase traffic", "Plant only rapid-growth trees"]'::jsonb,'Add a clean layer',1,37,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Where can food crops be grown more safely?','["On compacted roads", "In raised beds with imported soil", "Under demolished buildings", "Only below mature trees"]'::jsonb,'In raised beds with imported soil',1,38,'listening',0.55,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why may fast-growing trees fail during drought?','["Their roots cannot penetrate compacted soil", "They receive too much monitoring", "Their leaves store water", "They grow only in gardens"]'::jsonb,'Their roots cannot penetrate compacted soil',1,39,'listening',0.55,s.id,'cause_effect',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What do volunteers need for comparable data?','["Different tools at every site", "Consistent sampling instructions", "Fewer measurements", "No supervision"]'::jsonb,'Consistent sampling instructions',1,40,'listening',0.55,s.id,'summary_completion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='listening' join public.assessment_stimuli st on st.code='KLI-IELTS-L4' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_stimuli(code,title,content,stimulus_type,content_hidden) values('KLI-IELTS-R1','Reading Passage 1 — Restoring Urban Wetlands','Urban wetlands were once dismissed as unproductive land and were frequently drained for roads, housing, or industry. During the last several decades, however, researchers have documented services that these ecosystems provide. Wetland vegetation slows storm water, while soils and microorganisms retain or transform some pollutants before they enter rivers. Shallow water and varied plant structure also create habitat for insects, fish, and birds. These functions have encouraged cities to restore wetlands as part of flood management rather than relying entirely on concrete channels.

Restoration is more complicated than excavating a basin and adding water. A wetland depends on the timing, depth, and movement of water. If a site remains permanently deep, plants adapted to seasonal flooding may disappear. If water drains too quickly, invasive terrestrial species can dominate. Designers therefore study historical maps, groundwater, and rainfall before reshaping a site. They may remove fill, reconnect a stream to its floodplain, or create several elevations so that different plant communities can establish.

Public expectations can create another challenge. Residents sometimes prefer a tidy landscape with open water and short vegetation, whereas ecologists may favour dense plants, fallen wood, and temporarily muddy areas. Mosquitoes are also a common concern, although wetlands with predators and changing water levels do not necessarily produce more mosquitoes than neglected drains. Clear signs and community monitoring can explain why a restored site looks different from a conventional park.

Performance must be assessed over time. Early photographs may show vigorous growth, yet appearance alone says little about flood storage, nutrient removal, or biodiversity. Monitoring programmes measure water levels, plant survival, soil development, and animal use across several seasons. A project may require adjustment if one inlet erodes or if a small number of plants displace other species. Successful restoration is therefore adaptive: managers establish goals, observe results, and revise interventions.

Equity has become an important consideration. Green infrastructure can improve neighbourhoods, but it may also increase property values and place pressure on long-term residents. Some cities now pair restoration with affordable-housing policies, local employment, and guaranteed public access. The wetland is then evaluated not only as an ecological facility but also as part of a social landscape. This broader approach recognises that urban environmental projects succeed when hydrology, ecology, maintenance, and community priorities are considered together.','reading',false) on conflict(code) do update set title=excluded.title,content=excluded.content;
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'The passage mainly explains','["Why all wetlands should look like parks", "How urban wetland restoration combines ecological and social planning", "Why concrete channels are always ineffective", "How mosquitoes prevent restoration"]'::jsonb,'How urban wetland restoration combines ecological and social planning',1,41,'reading',0.58,s.id,'main_idea',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Wetland vegetation can help by','["accelerating storm water", "slowing storm water", "removing all rainfall", "preventing plant growth"]'::jsonb,'slowing storm water',1,42,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'TRUE, FALSE, or NOT GIVEN: A permanently deep site may disadvantage plants adapted to seasonal flooding.','["TRUE", "FALSE", "NOT GIVEN"]'::jsonb,'TRUE',1,43,'reading',0.58,s.id,'true_false_not_given',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Historical maps are studied primarily to understand','["former site conditions", "current house prices", "bird migration alone", "park opening hours"]'::jsonb,'former site conditions',1,44,'reading',0.58,s.id,'purpose',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'The word “dominate” is closest to','["become prevalent", "disappear completely", "remain unchanged", "be measured"]'::jsonb,'become prevalent',1,45,'reading',0.58,s.id,'vocabulary',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Residents may prefer wetlands that','["appear tidy and open", "contain fallen wood", "remain muddy", "have dense vegetation"]'::jsonb,'appear tidy and open',1,46,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What misconception about mosquitoes is discussed?','["All restored wetlands necessarily produce more mosquitoes", "Mosquitoes live only in rivers", "Predators increase mosquito numbers", "Signs eliminate mosquitoes"]'::jsonb,'All restored wetlands necessarily produce more mosquitoes',1,47,'reading',0.58,s.id,'inference',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which measure is NOT mentioned in monitoring?','["Water levels", "Plant survival", "Animal use", "Ticket sales"]'::jsonb,'Ticket sales',1,48,'reading',0.58,s.id,'negative_detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Adaptive restoration requires managers to','["avoid changing plans", "observe results and revise interventions", "measure appearance only", "remove all invasive plants immediately"]'::jsonb,'observe results and revise interventions',1,49,'reading',0.58,s.id,'summary',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'The word “it” in “it may also increase property values” refers to','["green infrastructure", "public access", "local employment", "affordable housing"]'::jsonb,'green infrastructure',1,50,'reading',0.58,s.id,'reference',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why are affordable-housing policies mentioned?','["To address possible displacement pressure", "To eliminate biodiversity", "To replace wetland maintenance", "To prevent public access"]'::jsonb,'To address possible displacement pressure',1,51,'reading',0.58,s.id,'purpose',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which statement matches the writer’s view?','["Ecological goals should be considered alone", "Urban restoration has both environmental and social dimensions", "Short-term appearance proves success", "Community preferences are irrelevant"]'::jsonb,'Urban restoration has both environmental and social dimensions',1,52,'reading',0.58,s.id,'writer_view',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Choose the best heading','["Wetlands as integrated urban systems", "The disappearance of every urban wetland", "A history of concrete production", "Why cities should avoid water"]'::jsonb,'Wetlands as integrated urban systems',1,53,'reading',0.58,s.id,'heading',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R1' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_stimuli(code,title,content,stimulus_type,content_hidden) values('KLI-IELTS-R2','Reading Passage 2 — The Development of Public Time','For much of human history, communities did not need every clock to show precisely the same time. Daily activity followed daylight, local bells, and the observable position of the sun. A town could set noon when the sun reached its highest point, even though another town some distance east or west experienced solar noon at a different moment. Such variation caused little difficulty while most journeys were slow and communication depended on physical travel.

Mechanical public clocks appeared in European towns during the late medieval period. Early machines were expensive and not especially accurate, but they served civic purposes. Bells announced religious observances, market openings, curfews, and meetings. Because clock faces were not always visible, sound mattered as much as visual display. The possession of a large clock also communicated wealth and administrative authority. Timekeeping gradually moved from monasteries and courts into shared urban space.

Industrialisation increased the demand for coordination. Factories expected large groups of workers to begin at a fixed hour, and expanding postal networks promised regular collection and delivery. The greatest pressure came from railways. A timetable connecting many towns could not function safely if each station used local solar time. Railway companies initially adopted the time of a major city, and national standard time later became law in many countries. The change was sometimes criticised as an artificial system imposed by distant institutions, but its practical advantages were substantial.

Telegraph networks made synchronisation more precise. An observatory could determine time through astronomical measurement and transmit an electrical signal to distant clocks. Public clocks at stations and civic buildings were corrected automatically or by local operators. Accuracy became a public service rather than merely a feature of private instruments. In the twentieth century, radio signals and eventually atomic clocks provided still more stable references.

Standardisation did not eliminate social differences in time. Factory owners and workers could disagree about whether workplace clocks were fair. Rural communities might follow agricultural rhythms even while official schedules used national time. Today digital devices update invisibly through networks, giving the impression that time is natural and uniform. In reality, the system is maintained through technical infrastructure, legal decisions, and international agreements.

The history of public time therefore illustrates more than improvement in clock technology. It shows how societies create shared standards when economic and communication networks expand. Precision became valuable because institutions required coordination, and each new method of synchronisation altered who controlled the public schedule.','reading',false) on conflict(code) do update set title=excluded.title,content=excluded.content;
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Before rapid transport, local time differences','["caused major railway accidents", "usually created little difficulty", "were prohibited by law", "were corrected by radio"]'::jsonb,'usually created little difficulty',1,54,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Early public clocks were valued partly because they','["were perfectly accurate", "communicated civic authority", "eliminated bells", "were inexpensive"]'::jsonb,'communicated civic authority',1,55,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'TRUE, FALSE, or NOT GIVEN: Every early public clock had a visible face.','["TRUE", "FALSE", "NOT GIVEN"]'::jsonb,'FALSE',1,56,'reading',0.58,s.id,'true_false_not_given',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Industrialisation increased the need for','["coordinated schedules", "local solar time only", "slower communication", "fewer postal services"]'::jsonb,'coordinated schedules',1,57,'reading',0.58,s.id,'summary',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why did railways create pressure for standard time?','["Connected timetables required consistency", "Trains measured solar noon", "Passengers rejected clocks", "Stations had no employees"]'::jsonb,'Connected timetables required consistency',1,58,'reading',0.58,s.id,'cause_effect',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'The word “imposed” most nearly means','["introduced by authority", "measured by sunlight", "removed gradually", "accepted privately"]'::jsonb,'introduced by authority',1,59,'reading',0.58,s.id,'vocabulary',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What enabled observatories to send time signals?','["Railway bells", "Telegraph networks", "Factory machinery", "Postal vehicles"]'::jsonb,'Telegraph networks',1,60,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Accuracy became described as','["a public service", "a rural tradition", "an unnecessary expense", "a private secret"]'::jsonb,'a public service',1,61,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'TRUE, FALSE, or NOT GIVEN: Standard time immediately ended every disagreement about workplace clocks.','["TRUE", "FALSE", "NOT GIVEN"]'::jsonb,'FALSE',1,62,'reading',0.58,s.id,'true_false_not_given',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Modern networked devices make time appear','["natural and uniform", "local and uncertain", "controlled by sunlight", "unrelated to agreements"]'::jsonb,'natural and uniform',1,63,'reading',0.58,s.id,'inference',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Which factor is NOT said to maintain modern time?','["Technical infrastructure", "Legal decisions", "International agreements", "Seasonal farming"]'::jsonb,'Seasonal farming',1,64,'reading',0.58,s.id,'negative_detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'The final paragraph argues that precision became valuable because','["institutions needed coordination", "clocks became decorative", "towns abandoned trade", "people stopped travelling"]'::jsonb,'institutions needed coordination',1,65,'reading',0.58,s.id,'conclusion',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Choose the best title','["How Societies Standardised Time", "Why Mechanical Clocks Failed", "The End of Public Schedules", "Agricultural Life without Institutions"]'::jsonb,'How Societies Standardised Time',1,66,'reading',0.58,s.id,'title',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R2' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_stimuli(code,title,content,stimulus_type,content_hidden) values('KLI-IELTS-R3','Reading Passage 3 — Citizen Science and Data Quality','Citizen science projects invite members of the public to contribute to research by observing wildlife, classifying images, measuring rainfall, or recording environmental conditions. Digital platforms allow thousands of volunteers to submit information across areas that professional researchers could not visit frequently. The resulting datasets can reveal migration patterns, seasonal changes, and rare events. Yet large numbers of observations do not automatically produce reliable evidence. Project design determines whether volunteer contributions can answer a scientific question.

One challenge is uneven participation. Volunteers often live near cities, roads, or popular natural areas, so accessible locations may be recorded repeatedly while remote places remain unobserved. Participants also differ in experience. A skilled birdwatcher may distinguish similar species that a beginner confuses. Researchers address these problems by requesting photographs, recording confidence levels, providing identification training, and using statistical models that account for observation effort. Some platforms direct volunteers toward poorly sampled locations, although participation remains voluntary.

The design of instructions is equally important. A request to report anything interesting produces different data from a protocol requiring a ten-minute count within a defined area. Standardised methods reduce variation, but overly complicated procedures may discourage participation. Effective projects test instructions with intended users and explain why each step matters. Mobile applications can prevent impossible entries, record time and location automatically, and remind participants to include occasions when nothing was observed. These zero observations are valuable because absence cannot be inferred from silence.

Validation combines automated and human review. Software may flag a species reported far outside its known range or a temperature inconsistent with nearby sensors. Experts then examine supporting evidence and may contact the observer. A flagged record is not necessarily false; unusual observations can represent genuine ecological change. For this reason, transparent projects preserve the original submission, document corrections, and distinguish verified records from those awaiting review.

Volunteer motivation affects long-term coverage. Participants are more likely to continue when they receive feedback, see maps based on their work, and understand how findings influence conservation or policy. Competition and badges can encourage activity, but they may also reward quantity over care. Project managers therefore balance recognition with messages about accuracy and complete reporting.

Citizen science is most powerful when treated as collaboration rather than free data collection. Researchers contribute clear questions, protocols, analysis, and feedback; volunteers contribute time, local knowledge, and geographic reach. When limitations are measured rather than ignored, public participation can produce evidence that complements professional surveys while also increasing scientific understanding in the wider community.','reading',false) on conflict(code) do update set title=excluded.title,content=excluded.content;
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What is the central argument?','["Volunteer data is always unreliable", "Citizen science can be valuable when limitations are managed", "Professional surveys are no longer needed", "Digital platforms solve every sampling problem"]'::jsonb,'Citizen science can be valuable when limitations are managed',1,67,'reading',0.58,s.id,'main_idea',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why may accessible places be overrepresented?','["Volunteers often live or travel nearby", "Researchers prohibit remote observations", "Wildlife avoids remote areas", "Applications delete remote records"]'::jsonb,'Volunteers often live or travel nearby',1,68,'reading',0.58,s.id,'cause_effect',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'How can projects address differences in experience?','["Ignore beginner observations", "Provide training and request photographs", "Accept only urban reports", "Remove confidence levels"]'::jsonb,'Provide training and request photographs',1,69,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'TRUE, FALSE, or NOT GIVEN: Volunteers are required to visit locations selected by researchers.','["TRUE", "FALSE", "NOT GIVEN"]'::jsonb,'FALSE',1,70,'reading',0.58,s.id,'true_false_not_given',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'A standardised protocol helps to','["reduce unwanted variation", "guarantee participation", "eliminate every error", "reward quantity"]'::jsonb,'reduce unwanted variation',1,71,'reading',0.58,s.id,'summary',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why can complicated procedures be harmful?','["They may discourage volunteers", "They make locations accessible", "They create zero observations", "They automate timestamps"]'::jsonb,'They may discourage volunteers',1,72,'reading',0.58,s.id,'cause_effect',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What can mobile applications record automatically?','["Scientific conclusions", "Time and location", "Volunteer motivation", "Expert corrections only"]'::jsonb,'Time and location',1,73,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Why are zero observations valuable?','["They indicate that a survey occurred without a sighting", "They prove a species is extinct", "They replace all positive records", "They increase competition"]'::jsonb,'They indicate that a survey occurred without a sighting',1,74,'reading',0.58,s.id,'inference',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'A record flagged by software','["is automatically false", "may represent a genuine unusual event", "must be deleted", "cannot be reviewed"]'::jsonb,'may represent a genuine unusual event',1,75,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'The word “transparent” most nearly means','["open about procedures and changes", "invisible to volunteers", "commercially successful", "simple to photograph"]'::jsonb,'open about procedures and changes',1,76,'reading',0.58,s.id,'vocabulary',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'What may be a disadvantage of badges?','["They can reward quantity over care", "They prevent feedback", "They reduce geographic reach", "They prohibit classification"]'::jsonb,'They can reward quantity over care',1,77,'reading',0.58,s.id,'inference',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Participants are more likely to continue when they','["receive feedback and see the use of their work", "submit only rare records", "avoid standard methods", "compete without guidance"]'::jsonb,'receive feedback and see the use of their work',1,78,'reading',0.58,s.id,'detail',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Citizen science is strongest when viewed as','["collaboration", "free labour only", "automated validation", "a replacement for research design"]'::jsonb,'collaboration',1,79,'reading',0.58,s.id,'writer_view',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_questions(test_id,prompt,options,correct_option,points,sort_order,competency,difficulty,section_id,item_type,randomize_options,stimulus_id) select t.id,'Choose the best heading for the whole passage','["Designing Reliable Citizen Science", "Why Public Observations Should Be Rejected", "The End of Professional Surveys", "Collecting Data without Instructions"]'::jsonb,'Designing Reliable Citizen Science',1,80,'reading',0.58,s.id,'heading',false,st.id from public.assessment_tests t join public.assessment_sections s on s.test_id=t.id and s.code='reading' join public.assessment_stimuli st on st.code='KLI-IELTS-R3' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_tasks(test_id,skill,stimulus,prompt,min_words,max_words,duration_seconds,rubric_id,sort_order,published)
select t.id,'writing','The table shows the percentage of commuters using four transport modes in Westbridge in 2010 and 2025. Bus: 32% to 38%; Private car: 46% to 31%; Bicycle: 12% to 19%; Walking: 10% to 12%.','Writing Task 1: Summarise the information by selecting and reporting the main features, and make comparisons where relevant.',150,300,1200,r.id,1,true from public.assessment_tests t join public.assessment_rubrics r on r.code='WRITING' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_tasks(test_id,skill,stimulus,prompt,min_words,max_words,duration_seconds,rubric_id,sort_order,published)
select t.id,'writing',null,'Writing Task 2: Some people believe universities should focus primarily on employment skills, while others believe broader academic knowledge is equally important. Discuss both views and give your own opinion.',250,500,2400,r.id,2,true from public.assessment_tests t join public.assessment_rubrics r on r.code='WRITING' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_tasks(test_id,skill,stimulus,prompt,min_words,max_words,duration_seconds,rubric_id,sort_order,published)
select t.id,'speaking',null,'Speaking Part 1: Answer questions about your home area, studies or work, daily routines, and use of public spaces.',null,null,300,r.id,3,true from public.assessment_tests t join public.assessment_rubrics r on r.code='SPEAKING' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_tasks(test_id,skill,stimulus,prompt,min_words,max_words,duration_seconds,rubric_id,sort_order,published)
select t.id,'speaking','Describe a place where you can concentrate well. Say where it is, when you use it, what it is like, and explain why it helps you concentrate.','Speaking Part 2: Prepare for one minute, then speak for one to two minutes using the task card.',null,null,240,r.id,4,true from public.assessment_tests t join public.assessment_rubrics r on r.code='SPEAKING' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
insert into public.assessment_tasks(test_id,skill,stimulus,prompt,min_words,max_words,duration_seconds,rubric_id,sort_order,published)
select t.id,'speaking',null,'Speaking Part 3: Discuss how environments affect concentration, whether schools and workplaces should provide quiet areas, and how technology has changed attention.',null,null,300,r.id,5,true from public.assessment_tests t join public.assessment_rubrics r on r.code='SPEAKING' where t.code='EN-IELTS-ACADEMIC-PRACTICE';
update public.assessment_stimuli set estimated_duration_seconds=greatest(5,ceil(array_length(regexp_split_to_array(trim(audio_script),'\s+'),1)/2.3)::int),timing_map=jsonb_build_array(jsonb_build_object('start_seconds',0,'end_seconds',greatest(5,ceil(array_length(regexp_split_to_array(trim(audio_script),'\s+'),1)/2.3)::int))) where code like 'KLI-IELTS-L%' and audio_script is not null;
